# Generated by Django 6.0.2 on 2026-02-28 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('html_url', models.URLField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('prompt_model', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('total_issues', models.PositiveIntegerField(default=0)),
                ('matched_issues', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_tasks', to='core.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('issue_url', models.URLField()),
                ('state', models.CharField(default='open', max_length=20)),
                ('linked_pr_url', models.URLField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('resolution_summary', models.TextField(blank=True)),
                ('resolution_status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_candidates', to='core.scantask')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('scan_task', 'issue_number'), name='unique_issue_number_per_scan')],
            },
        ),
    ]
