# Generated by Django 6.0.2 on 2026-02-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('github_api_key', models.CharField(max_length=255)),
                ('llm_provider', models.CharField(choices=[('ollama', 'Ollama'), ('vllm', 'vLLM')], default='ollama', max_length=20)),
                ('llm_base_url', models.URLField(default='http://localhost:11434/v1')),
                ('llm_model', models.CharField(default='llama3.1:8b', max_length=120)),
                ('llm_api_key', models.CharField(blank=True, max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('max_issues_per_scan', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
