# Generated by Django 6.0.2 on 2026-02-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scantask_cancel_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
