# Generated by Django 6.0.2 on 2026-03-08 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_globalsettings_refactor_agentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='error_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scantask',
            name='processed_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scantask',
            name='skipped_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scantask',
            name='uploaded_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScanStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('scan_start', 'Scan started'), ('fetch_issues_page', 'Fetching issues page'), ('fetch_issues_done', 'Issues fetched'), ('issue_start', 'Processing issue'), ('fetch_comments', 'Fetching comments'), ('fetch_timeline', 'Fetching timeline'), ('fetch_pr', 'Fetching PR details'), ('fetch_pr_files', 'Fetching PR files'), ('ai_queued', 'AI analysis queued'), ('ai_running', 'AI analysis running'), ('ai_done', 'AI analysis complete'), ('ai_error', 'AI analysis error'), ('quality_gate', 'Quality gate check'), ('upload_start', 'Problem99 upload started'), ('upload_ok', 'Problem99 upload succeeded'), ('upload_skip', 'Problem99 upload skipped'), ('upload_fail', 'Problem99 upload failed'), ('issue_done', 'Issue processing done'), ('scan_done', 'Scan completed'), ('scan_error', 'Scan error'), ('scan_stopped', 'Scan stopped')], max_length=30)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='core.scantask')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['scan_task', 'created_at'], name='core_scanst_scan_ta_6a739c_idx')],
            },
        ),
    ]
