# Generated by Django 6.0.2 on 2026-03-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_scansteplog_and_progress_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='current_issue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scantask',
            name='current_phase',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
